PRODUCT := out

CXX := g++
LINKER := g++
INCDIRS := -I.
CXXFLAGS := -std=c++11 -Wall -Wextra
SRCFILES := $(wildcard *.cpp)
OBJFILES := $(patsubst %.cpp, %.o, $(SRCFILES))
DEPFILES :=
ch1.1 : ch1.1.cpp
	g++ -Wall -Wextra -pedantic ch1.1.cpp -o ch1.1 

